print("This is an average marks calculator.")
print(" ")
mark1 = float(input("What is your mark for course 1: "))
mark2 = float(input("What is your mark for course 2: "))
mark3 = float(input("What is your mark for course 3: "))
mark4 = float(input("What is your mark for course 4: "))
print(" ")
avg = ((mark1 + mark2 + mark3 + mark4)/4)
print("Your final mark is " + str(avg))